---

- name: Create host in controller
  hosts:
    - all
  gather_facts: false

  tasks:
    - name: Set fact when needed
      ansible.builtin.set_fact:
        resource_state: present
      when:
        - resource_state is not defined

    - name: Set host facts
      ansible.builtin.set_fact:
        controller_hosts:
          - name: "edge-{{ mac_address }}"
            inventory: Edge Devices
            enabled: true
            state: "{{ resource_state | default('present') }}"
            variables:
              ansible_host: "{{ ip_address }}"

    - name: Run the redhat_cop.controller_configuration.hosts role
      ansible.builtin.include_role:
        name: redhat_cop.controller_configuration.hosts


    - name: Set host facts
      ansible.builtin.set_fact:
        controller_inventories:
          - name: "edge-{{ mac_address }}"
            description: "Inventory containing just device edge-{{ mac_address }}"
            organization: "<YOUR_ORG>"
            state: present

    - name: Create dedicated inventory
      ansible.builtin.include_role:
        name: redhat_cop.controller_configuration.inventories

    - name: Set host facts
      ansible.builtin.set_fact:
        controller_hosts:
          - name: "edge-{{ mac_address }}"
            inventory: "edge-{{ mac_address }}"
            enabled: true
            state: "{{ resource_state | default('present') }}"
            variables:
              ansible_host: "{{ ip_address }}"

    - name: Run the redhat_cop.controller_configuration.hosts role
      ansible.builtin.include_role:
        name: redhat_cop.controller_configuration.hosts
